# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-02 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(max_length=255, verbose_name='Description')),
                ('price', models.IntegerField(default=0, verbose_name='Price')),
            ],
            options={
                'verbose_name': 'Payment Plan',
            },
        ),
    ]
