# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-03 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0017_remove_product_plan'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(max_length=255, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Book',
            },
        ),
        migrations.DeleteModel(
            name='Payment_Plan',
        ),
    ]
