# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-03 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0019_remove_product_books'),
        ('core', '0002_auto_20181003_0233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(max_length=255, verbose_name='Description')),
                ('price', models.IntegerField(default=0, verbose_name='Price')),
            ],
            options={
                'verbose_name': 'Payment Plan',
            },
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
