# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-02 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_auto_20170821_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.URLField(default='22222'),
            preserve_default=False,
        ),
    ]
