# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-09 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('catalogue', '0013_auto_20170821_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='plan',
            field=models.ManyToManyField(blank=True, to='core.Payment_Plan', verbose_name='Plan'),
        ),
        migrations.AddField(
            model_name='product',
            name='url_video',
            field=models.CharField(default='url', max_length=250),
            preserve_default=False,
        ),
    ]
