# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-02 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('catalogue', '0014_product_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='video_url',
        ),
        migrations.AddField(
            model_name='product',
            name='options',
            field=models.ManyToManyField(blank=True, to='core.Payment_Plan', verbose_name='Plan'),
        ),
    ]
