# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-02 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0015_auto_20181002_0907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='options',
            new_name='plan',
        ),
    ]
