# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-03 02:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0016_auto_20181002_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='plan',
        ),
    ]
