# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-03 03:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0018_product_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='books',
        ),
    ]
