# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-08 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0020_product_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url_video',
            field=models.CharField(default='1', max_length=250),
            preserve_default=False,
        ),
    ]
